package dev.ancaria.coderpack.plugin

import dev.ancaria.coderpack.verify.Ids
import dev.ancaria.coderpack.verify.Ranges
import dev.ancaria.coderpack.verify.Verifier
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes `META-INF/declaration.toml` into a directory that becomes a resource root.
 *
 * The descriptor is generated rather than kept by hand because it repeats things
 * the build already knows (the version above all) and a version that
 * disagrees with the jar it is inside is a bug nobody sees until a player
 * reports the wrong number in the launcher.
 */
@CacheableTask
abstract class Descriptor : DefaultTask() {

    @get:Input
    abstract val modId: Property<String>

    @get:Input
    abstract val displayName: Property<String>

    @get:Input
    abstract val modVersion: Property<String>

    @get:Input
    @get:Optional
    abstract val modDescription: Property<String>

    @get:Input
    abstract val entrypoint: Property<String>

    @get:Input
    abstract val authors: ListProperty<String>

    @get:Input
    @get:Optional
    abstract val website: Property<String>

    @get:Input
    @get:Optional
    abstract val repository: Property<String>

    @get:Input
    abstract val conflicts: ListProperty<String>

    /** The range of API contracts, written as `api`. Defaults to this major alone. */
    @get:Input
    abstract val apiRange: Property<String>

    /** The range of launcher releases, written as `loader`. Nothing when unset. */
    @get:Input
    @get:Optional
    abstract val loaderRange: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val id = modId.orNull.orEmpty()
        if (!Ids.valid(id)) {
            throw GradleException(
                "sacred.id is “$id”. Use lowercase letters, digits and hyphens. The " +
                    "launcher writes this value into its enabled list."
            )
        }
        for (other in conflicts.get()) {
            if (!Ids.valid(other)) {
                throw GradleException(
                    "sacred.conflicts names “$other”. A conflict must use another mod’s " +
                        "id: lowercase letters, digits and hyphens."
                )
            }
            if (other == id) {
                throw GradleException("sacred.conflicts names this mod itself")
            }
        }
        val main = entrypoint.orNull.orEmpty()
        if (main.isBlank()) {
            throw GradleException(
                "sacred.entrypoint is missing. Set it to the class that implements SacredMod."
            )
        }

        // Checked before it is written rather than after it is packed. Both end
        // in a failed build, but only one of them fails on the line somebody
        // typed, with the range they typed in the message.
        val api = apiRange.getOrElse(API)
        val builds = try {
            Verifier.builds(api)
        } catch (bad: IllegalArgumentException) {
            throw GradleException("sacred.apiRange isn’t a valid version range: ${bad.message}")
        }
        if (!builds) {
            throw GradleException(
                "sacred.apiRange is “$api”, but this toolchain builds API ${Verifier.API}. " +
                    "Include ${Verifier.API} in the range or use the toolchain named by the range."
            )
        }
        val loader = loaderRange.orNull?.takeIf { it.isNotBlank() }
        if (loader != null) {
            try {
                Ranges.range(loader)
            } catch (bad: IllegalArgumentException) {
                throw GradleException("sacred.loaderRange isn’t a valid version range: ${bad.message}")
            }
        }

        val lines = buildList {
            add("# Generated by the Sacred mod plugin. Edits here are overwritten.")
            add(pair("id", id))
            add(pair("name", displayName.getOrElse(id)))
            add(pair("version", modVersion.getOrElse("0")))
            modDescription.orNull?.takeIf { it.isNotBlank() }?.let { add(pair("description", it)) }
            add(pair("entrypoint", main))
            add(pair("api", api))
            loader?.let { add(pair("loader", it)) }
            authors.get().filter { it.isNotBlank() }.takeIf { it.isNotEmpty() }?.let {
                add("authors = [" + it.joinToString(", ") { name -> quote(name) } + "]")
            }
            website.orNull?.takeIf { it.isNotBlank() }?.let { add(pair("website", it)) }
            repository.orNull?.takeIf { it.isNotBlank() }?.let { add(pair("repository", it)) }
            conflicts.get().filter { it.isNotBlank() }.takeIf { it.isNotEmpty() }?.let {
                add("conflicts = [" + it.joinToString(", ") { other -> quote(other) } + "]")
            }
        }

        val target = outputDirectory.get().asFile.resolve(DESCRIPTOR)
        target.parentFile.mkdirs()
        target.writeText(lines.joinToString("\n", postfix = "\n"))
    }

    private fun pair(key: String, value: String) = "$key = ${quote(value)}"

    private fun quote(value: String) =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    companion object {
        const val DESCRIPTOR = "META-INF/declaration.toml"

        /**
         * The `api` range written when a mod author sets none: the contract this
         * plugin compiles against and nothing else, which is what every
         * descriptor meant back when the field was a bare number.
         *
         * Not the artifact version: `dev.ancaria.coderpack:api` is at 0.100.0 and
         * keeps moving, while this changes only when the contract breaks.
         *
         * An author may set `sacred.apiRange` and widen it, because they are the
         * only one who can know whether their code survives the next major. What
         * they may not do is name a contract nothing here compiled against, and
         * `generate` above refuses that before it writes a line. The loader
         * believes the descriptor, so a claim in it has to be one somebody could
         * check.
         *
         * The default itself lives in `Verifier.API_RANGE`, next to the linter
         * that checks it: the range stamped into a mod and the contract the
         * linter demands have to agree, or every jar this plugin builds fails its
         * own check. Raising the contract means that edit, plus `Api.VERSION` in
         * the loader and `mods.API` in the launcher.
         */
        // A val rather than a const: Verifier derives it from the contract
        // number instead of repeating it as a literal, which makes it a runtime
        // value in Java and so not a Kotlin compile-time constant. Nothing here
        // needs one.
        val API = Verifier.API_RANGE
    }
}
